"""add vehicle_year to enquiries

Revision ID: 3544b0a7967e
Revises: a57f0200ad37
Create Date: 2026-08-10 13:43:16.304544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3544b0a7967e'
down_revision = 'a57f0200ad37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_year', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_column('vehicle_year')

    # ### end Alembic commands ###
