"""add apex account name and last synced to client companies

Revision ID: 629a07c9db14
Revises: 3544b0a7967e
Create Date: 2026-08-11 10:29:41.313489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629a07c9db14'
down_revision = '3544b0a7967e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apex_account_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('apex_last_synced_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_companies', schema=None) as batch_op:
        batch_op.drop_column('apex_last_synced_at')
        batch_op.drop_column('apex_account_name')

    # ### end Alembic commands ###
