"""add apex contract code to client companies

Revision ID: 9068381c4f3d
Revises: e0794c1bf3eb
Create Date: 2026-08-11 13:02:46.802833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9068381c4f3d'
down_revision = 'e0794c1bf3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apex_contract_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_companies', schema=None) as batch_op:
        batch_op.drop_column('apex_contract_code')

    # ### end Alembic commands ###
