"""initial schema

Revision ID: a57f0200ad37
Revises: 
Create Date: 2026-08-07 15:57:56.993639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57f0200ad37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_company_id', 'feature_key', name='uq_feature_flag_per_client')
    )
    op.create_table('client_sla_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=50), nullable=False),
    sa.Column('target_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_company_id', 'metric_key', name='uq_sla_target_per_client')
    )
    op.create_table('enquiry_form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_company_id', 'field_key', name='uq_form_field_per_client')
    )
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('WGTK_ADMIN', 'WGTK_GENERAL', 'CLIENT_ADMIN', 'CLIENT_GENERAL', name='userrole'), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'QUOTED', 'ACCEPTED', 'DECLINED_BY_CLIENT', 'DECLINED_BY_WGTK', 'SCHEDULED', 'ETA_EXPIRED', 'COMPLETED', name='enquirystatus'), nullable=False),
    sa.Column('vehicle_registration', sa.String(length=20), nullable=True),
    sa.Column('vehicle_make_model', sa.String(length=200), nullable=True),
    sa.Column('location_address', sa.String(length=500), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('on_site_contact_name', sa.String(length=200), nullable=True),
    sa.Column('on_site_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('extra_fields_json', sa.Text(), nullable=True),
    sa.Column('eta_date', sa.Date(), nullable=True),
    sa.Column('eta_is_same_day', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_eta_expired', sa.Boolean(), nullable=False),
    sa.Column('decline_reason_type', sa.Enum('PRICE', 'ETA', 'OTHER', name='declinereasontype'), nullable=True),
    sa.Column('decline_reason_text', sa.Text(), nullable=True),
    sa.Column('wgtk_decline_reason_text', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enquiries_client_company_id'), ['client_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_status'), ['status'], unique=False)

    op.create_table('email_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('enquiry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiry_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('NEW', 'QUOTED', 'ACCEPTED', 'DECLINED_BY_CLIENT', 'DECLINED_BY_WGTK', 'SCHEDULED', 'ETA_EXPIRED', 'COMPLETED', name='enquirystatus'), nullable=True),
    sa.Column('to_status', sa.Enum('NEW', 'QUOTED', 'ACCEPTED', 'DECLINED_BY_CLIENT', 'DECLINED_BY_WGTK', 'SCHEDULED', 'ETA_EXPIRED', 'COMPLETED', name='enquirystatus'), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enquiry_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enquiry_status_history_enquiry_id'), ['enquiry_id'], unique=False)

    op.create_table('job_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('V5', 'LETTER_OF_AUTHORITY', 'JOB_SHEET', 'COMPLETION_REPORT', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('visibility', sa.Enum('INTERNAL', 'CLIENT_VISIBLE', name='notevisibility'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING_ACCEPTANCE', 'ACCEPTED', name='documentstatus'), nullable=True),
    sa.Column('accepted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_documents_enquiry_id'), ['enquiry_id'], unique=False)

    op.create_table('job_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('INTERNAL', 'CLIENT_VISIBLE', name='notevisibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_notes_enquiry_id'), ['enquiry_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.Enum('WGTK_ADMIN', 'WGTK_GENERAL', 'CLIENT_ADMIN', 'CLIENT_GENERAL', name='userrole'), nullable=True),
    sa.Column('enquiry_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.Enum('NEW_ENQUIRY', 'QUOTE_SENT', 'ACCEPTED', 'DECLINED', 'ETA_EXPIRED', 'APPOINTMENT_SET', 'RESCHEDULED', 'COMPLETED', name='notificationtype'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_client_company_id'), ['client_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_client_company_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('job_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_notes_enquiry_id'))

    op.drop_table('job_notes')
    with op.batch_alter_table('job_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_documents_enquiry_id'))

    op.drop_table('job_documents')
    with op.batch_alter_table('enquiry_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enquiry_status_history_enquiry_id'))

    op.drop_table('enquiry_status_history')
    op.drop_table('email_outbox')
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enquiries_status'))
        batch_op.drop_index(batch_op.f('ix_enquiries_client_company_id'))

    op.drop_table('enquiries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('service_types')
    op.drop_table('enquiry_form_fields')
    op.drop_table('client_sla_targets')
    op.drop_table('client_feature_flags')
    op.drop_table('client_companies')
    # ### end Alembic commands ###
