"""add apex change-detection fields to enquiries

Revision ID: e0794c1bf3eb
Revises: 629a07c9db14
Create Date: 2026-08-11 12:04:01.051784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0794c1bf3eb'
down_revision = '629a07c9db14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apex_last_modified_at', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('apex_snapshot_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_column('apex_snapshot_json')
        batch_op.drop_column('apex_last_modified_at')

    # ### end Alembic commands ###
